services:
  backend:
    container_name: backend
    depends_on:
        database:
            condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Compose
    build:
        context: ../.
        dockerfile: ./WorkSchedule.Api/Dockerfile
    networks:
      - workschedule-network